#ifndef MACRO_DEFINITIONS_H_GUARD
#define MACRO_DEFINITIONS_H_GUARD

#define COLLISION_DEBUG_INFORMATION 0
#define ERASURE_DEBUG_INFORMATION 0
#define OPEN_GL_VERSION 0 
#define OPEN_GL_DEBUG_INFO 0
#define OPEN_GL_FILTERED_DEBUG 1
#define SCORE_DEBUG_PRINTOUT 0
#endif